Project2/Models/Insert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project2.Models
{
    public class Insert
    {
        [Required(ErrorMessage = "Enter the name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Enter the Phone Number")]
        public string Phone { get; set; }

        [EmailAddress(ErrorMessage = "Enter valid address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter the Username")]
        public string Username { get; set; }
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Password mismatch")]
        public string ConfirmPassword { get; set; }
        public string Msg { get; set; }
    }
}

Project2/Models/InsertBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project2.Models
{
    public class InsertBook
    {
        [Required(ErrorMessage = "Enter the Name")]
        public string BName { get; set; }
        [Required(ErrorMessage = "Enter the Author Name")]
        public string BAuthor { get; set; }
        [Required(ErrorMessage = "Required")]
        public string BImage { get; set; }
        [Required(ErrorMessage = "Required")]
        public string BDescr { get; set; }
        [Required(ErrorMessage = "Required")]
        public string BPrice { get; set; }
        public string BStatus { get; set; }
        public string Msg { get; set; }
    }
}

Project2/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project2.Models
{
    public class Login
    {
        [Required(ErrorMessage = "Enter the Username")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Enter the Password")]
        public string Password { get; set; }
        public string Msg { get; set; }
    }
}

Project2/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project2.Models;


namespace Project2.Controllers
{
    public class AdminHomeController : Controller
    {
        // GET: AdminHome
        Mvcproject1Entities dbobj = new Mvcproject1Entities();
        public ActionResult Home()
        {
            return View();
        }
    }
}

Project2/Controllers/AllBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project2.Models;

namespace Project2.Controllers
{
    public class AllBooksController : Controller
    {
        Mvcproject1Entities dbobj = new Mvcproject1Entities();
        // GET: AllBooks
        public ActionResult DisplayAll_Load(Book ob)
        {
            return View(dbobj.Books.ToList());
        }
    }
}

Project2/Controllers/InsertBookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project2.Models;

namespace Project2.Controllers
{
    public class InsertBookController : Controller
    {
        // GET: InsertBook
        Mvcproject1Entities dbobj = new Mvcproject1Entities();
        public ActionResult insert_Pageload()
        {
            return View();
        }
        
        public ActionResult insert_click(InsertBook objcls, HttpPostedFileBase file)
        {
            if(!ModelState.IsValid)
            {
                if (file.ContentLength > 0)
                {
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/PHS");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);

                    var fullpath = Path.Combine("~\\PHS", fname);
                    objcls.BImage = fullpath;//Set
                }
                //Get
                dbobj.sp_InsertBook(objcls.BName, objcls.BAuthor, objcls.BImage, objcls.BDescr, objcls.BPrice,objcls.BStatus);
                objcls.Msg = "Successfully inserted";
                //return View("insert_Pageload", objcls);
                return RedirectToAction("Home");
            }
            return View("insert_Pageload", objcls);
        }
    }
}

Project2/Controllers/InsertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project2.Models;

namespace Project2.Controllers
{
    public class InsertController : Controller
    {
        Mvcproject1Entities dbobj = new Mvcproject1Entities();
        // GET: Insert
        public ActionResult insert_Pageload()
        {
            return View();
        }
        public ActionResult insert_click(Insert objcls, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                //Get
                dbobj.sp_Insert(objcls.Name, objcls.Phone, objcls.Email, objcls.Username, objcls.Password);
                objcls.Msg = "Successfully inserted";
                return View("insert_Pageload", objcls);
            }

            return View("insert_Pageload", objcls);
        }
    }
}

Project2/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project2.Models;

namespace Project2.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        Mvcproject1Entities dbobj = new Mvcproject1Entities();
        // GET: Login
        public ActionResult Login_Pageload()
        {
            return View();
        }
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Login_click(Login objcls)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_Login(objcls.Username, objcls.Password, op);//Get
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    Session["uname"] = objcls.Username;
                    return RedirectToAction("Home");
                }
                else
                {
                    ModelState.Clear();
                    //objcls.Msg = "Invalid Login";
                    return View("Login_Pageload", objcls);
                }
            }
            return View("Login_Pageload", objcls);
        }
    }
}

Project2/Views/AdminHome/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Main Login</h2>
<div>
    @Html.ActionLink("Old User", "Login_Pageload", "Login")
</div>
<div>
    @Html.ActionLink("New User", "insert_Pageload", "Insert")
</div>

Project2/Views/AllBooks/DisplayAll_Load.cshtml
@model IEnumerable<Project2.Book>
@{
    ViewBag.Title = "DisplayAll_Load";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>DisplayAllBooks</h1>
<div>
    @using (Html.BeginForm("DisplayAll_Load", "AllBooks", FormMethod.Get))
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.BName)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.BAuthor)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.BImage)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.BDescr)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.BPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.BStatus)
                </th>
            </tr>
            @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BAuthor)
            </td>
            <td>
                <img src="@Url.Content(item.BImage)" alt="Image" height="150px" width="150px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BDescr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BStatus)
            </td>
        </tr>
            }
        </table>
    }
</div>

Project2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Project2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Project2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Project2/Views/Insert/insert_Pageload.cshtml
@model Project2.Models.Insert
@{
    ViewBag.Title = "insert_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New User</h2>
<div>
    @using (Html.BeginForm("insert_click", "Insert", FormMethod.Post))
    {
        <div>
            <label>Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name)
        </div>
        <div>
            <label>Phone:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Phone)
            @Html.ValidationMessageFor(m => m.Phone)
        </div>
        <div>
            <label>Email:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
        </div>
        <div>
            <label>Username:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Username)
            @Html.ValidationMessageFor(m => m.Username)
        </div>
        <div>
            <label>Password:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password)
        </div>
        <div>
            <label>ConfirmPassword:</label>
        </div>
        <div>
            @Html.PasswordFor(m => m.ConfirmPassword)
            @Html.ValidationMessageFor(m => m.ConfirmPassword)
        </div>
        <div>
            <input type="submit" value="Insert" />
            @Html.DisplayFor(m => m.Msg)
        </div>
    }
</div>

Project2/Views/InsertBook/insert_Pageload.cshtml
@model Project2.Models.InsertBook
@{
    ViewBag.Title = "insert_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Books</h2>
<div>
    @using (Html.BeginForm("insert_click", "InsertBook", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            <label>Book Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m =>m.BName)
            @Html.ValidationMessageFor(m =>m.BName)
        </div>
        <div>
            <label>Book Author:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.BAuthor)
            @Html.ValidationMessageFor(m => m.BAuthor)
        </div>
        <div>
            <label>Book Image:</label>
        </div>
        <div>
            @Html.TextBox("file", "", new { Type = "file" })
        </div>
        <div>
            <label>Book Description:</label>
        </div>
        <div>
            @Html.TextBoxFor(m =>m.BDescr)
            @Html.ValidationMessageFor(m =>m.BDescr)
        </div>
        <div>
            <label>Book Price:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.BPrice)
            @Html.ValidationMessageFor(m => m.BPrice)
        </div>
        <div>
            <label>Book Status:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.BStatus)
            @Html.ValidationMessageFor(m => m.BStatus)
        </div>
        <div>
            <input type="submit" value="Insert" />
            @Html.DisplayFor(m => m.Msg)
        </div>
    }
</div>

Project2/Views/Login/Home.cshtml
@model Project2.Models.Login
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Home</h2>
<div>
    @Html.ActionLink("View Books", "DisplayAll_Load", "AllBooks")
</div>
<div>
    @Html.ActionLink("Add Books", "insert_Pageload", "InsertBook")
</div>

Project2/Views/Login/Login_Pageload.cshtml
@model Project2.Models.Login
@{
    ViewBag.Title = "Login_Pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sign In</h2>
<div>
    @using (Html.BeginForm("Login_click", "Login", FormMethod.Post))
    {
        <div>
            <label>User Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Username)
            @Html.ValidationMessageFor(m => m.Username)
        </div>
        <div>
            <label>Password:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password)
        </div>
        <div>
            <input type="submit" value="Login" />
            @Html.DisplayFor(m => m.Msg)
        </div>
    }
</div>

Project2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>